version: '3'
services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  backend:
    build: ./backend
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - JWT_SECRET=require('crypto').randomBytes(64).toString('hex')
      - JWT_EXPIRES_IN=60m
      - DB_URI=mongodb+srv://ezkript:5VgUNxiZByy8jn1y@cluster0.llr1ysu.mongodb.net/
